import { NextResponse } from "next/server";
import { getAuthenticatedFirestoreForRequest } from "@/lib/firebaseServerApp";
import { financeErrorResponse } from "@/lib/financeApiError";
import { toDateKey, roundCurrency, DEFAULT_BRANCH_ID, type FinanceDailyClosing } from "@/lib/finance";
import { getDailyClosingsForRange } from "@/services/financeClosingService";
import { getFinanceAccounts } from "@/services/financeAccountsService";
import { getPostedTransactionsForRange } from "@/services/financeTransactionsService";
import { getZomatoImports, getItemSalesForDateRange } from "@/services/zomatoService";
import { getSwiggyImports, getSwiggyItemSalesForDateRange } from "@/services/swiggyService";

// ─── Platform (Zomato/Swiggy) real settled revenue ─────────────────────────────
//
// Daily Closing's zomatoSales/swiggySales is a manually entered GROSS guess
// (revenue recognized that day, before the platform's commission/GST/ads cut
// is even known). Rather than estimate a net figure from that guess, P&L now
// recognizes Zomato/Swiggy revenue only once it's real:
//   - "actual"  — this day's platform sales (from the imported Item Sales /
//                 Past Orders report) fall inside a payout period that has
//                 already been settled — net = that day's real CSV revenue
//                 × (1 − that settlement's own deduction %).
//   - "pending" — not settled yet (or nothing imported for this day at all)
//                 — contributes ₹0 to revenue. It'll switch to "actual" the
//                 moment that week's payout is recorded, with no guessing
//                 in between.
// The manually entered Daily Closing figure is no longer used for revenue
// recognition at all — it still exists for Escrow bookkeeping (Finance
// Defaults' zomato_sales/swiggy_sales events) but has no bearing on P&L.
type PlatformMode = "actual" | "pending";

interface PlatformImportLike {
  id: string;
  reportStartDate: string;
  reportEndDate: string;
  deductionPct?: number;
}

interface PlatformItemSaleLike {
  date: string;
  importId: string;
  revenue: number;
}

interface PlatformDayRevenue {
  net: number;
  deductionPct: number;
  mode: PlatformMode;
  sourceStart: string | null;
  sourceEnd: string | null;
}

/** Builds a date -> real settled revenue map from imported item-sales rows, counting only rows whose import has actually been settled (has a deductionPct) — unsettled and soft-deleted imports are silently excluded. */
function buildSettledRevenueByDate(
  imports: PlatformImportLike[],
  itemSales: PlatformItemSaleLike[],
): Map<string, PlatformDayRevenue> {
  const settledById = new Map(
    imports.filter((i) => typeof i.deductionPct === "number").map((i) => [i.id, i]),
  );

  const byDate = new Map<string, PlatformDayRevenue>();
  for (const row of itemSales) {
    const imp = settledById.get(row.importId);
    if (!imp) continue; // not settled yet, or belongs to a soft-deleted import — excluded entirely
    const net = roundCurrency(row.revenue * (1 - imp.deductionPct!));
    const existing = byDate.get(row.date);
    byDate.set(row.date, {
      net: roundCurrency((existing?.net ?? 0) + net),
      deductionPct: imp.deductionPct!,
      mode: "actual",
      sourceStart: imp.reportStartDate,
      sourceEnd: imp.reportEndDate,
    });
  }
  return byDate;
}

function lookupPlatformRevenue(byDate: Map<string, PlatformDayRevenue>, date: string): PlatformDayRevenue {
  return byDate.get(date) ?? { net: 0, deductionPct: 0, mode: "pending", sourceStart: null, sourceEnd: null };
}

export const dynamic = "force-dynamic";

// ─── Shared aggregation helper (same pattern as financeDashboardService) ──────

function sumByLabel(items: Array<{ label: string; amount: number }>): Array<{ label: string; amount: number }> {
  const totals = new Map<string, number>();
  for (const item of items) {
    totals.set(item.label, roundCurrency((totals.get(item.label) ?? 0) + item.amount));
  }
  return Array.from(totals.entries())
    .map(([label, amount]) => ({ label, amount }))
    .filter((item) => item.amount > 0)
    .sort((a, b) => b.amount - a.amount);
}

// ─── GET /api/finance/reports/pnl ─────────────────────────────────────────────

/**
 * Comprehensive P&L report for a date range.
 *
 * Mirrors the data-blending logic in financeDashboardService:
 *   - Daily Closing (fin_daily_closing): all revenue streams + cash expenses.
 *   - Transactions (fin_transactions): posted income/expense from non-cash
 *     accounts that were NOT auto-generated by Daily Closing itself (those
 *     are already counted in the closing totals — excluding them prevents
 *     double-counting). Transfers are excluded from P&L as always.
 *
 * The two sources are intentionally NOT mixed at the row level — the caller
 * sees closing rows for the day-by-day table and a pre-aggregated summary
 * (with category breakdowns) for the totals sections. The frontend never
 * has to know about account types or auto-post sources.
 */
export async function GET(request: Request) {
  try {
    const { cleanup, firestore } = await getAuthenticatedFirestoreForRequest(request);
    try {
      const url = new URL(request.url);
      const today = toDateKey();
      const dateFrom = url.searchParams.get("dateFrom") ?? today;
      const dateTo = url.searchParams.get("dateTo") ?? today;
      const branchId = DEFAULT_BRANCH_ID;

      // Fetch all sources in parallel
      const [rawClosings, accounts, rangeTransactions, zomatoImports, swiggyImports, zomatoItemSales, swiggyItemSales] = await Promise.all([
        getDailyClosingsForRange(dateFrom, dateTo, firestore, branchId),
        getFinanceAccounts({ branchId }, firestore),
        getPostedTransactionsForRange(dateFrom, dateTo, firestore, branchId),
        getZomatoImports(firestore),
        getSwiggyImports(firestore),
        getItemSalesForDateRange(dateFrom, dateTo, firestore),
        getSwiggyItemSalesForDateRange(dateFrom, dateTo, firestore),
      ]);

      const zomatoByDate = buildSettledRevenueByDate(zomatoImports, zomatoItemSales);
      const swiggyByDate = buildSettledRevenueByDate(swiggyImports, swiggyItemSales);

      const closingsWithSettled = rawClosings.map((c) => {
        const zomato = lookupPlatformRevenue(zomatoByDate, c.date);
        const swiggy = lookupPlatformRevenue(swiggyByDate, c.date);
        return {
          ...c,
          zomatoActualRevenue: zomato.net,
          zomatoDeductionPct: zomato.deductionPct,
          zomatoMode: zomato.mode,
          zomatoSourceStart: zomato.sourceStart,
          zomatoSourceEnd: zomato.sourceEnd,
          swiggyActualRevenue: swiggy.net,
          swiggyDeductionPct: swiggy.deductionPct,
          swiggyMode: swiggy.mode,
          swiggySourceStart: swiggy.sourceStart,
          swiggySourceEnd: swiggy.sourceEnd,
        };
      });

      const accountTypeById = new Map(accounts.map((a) => [a.id, a.type]));
      const isCashAccount = (accountId: string | null) =>
        accountId ? accountTypeById.get(accountId) === "cash" : false;

      // Exclude daily_closing auto-posts (already counted in closing totals)
      // and transfers (not P&L items)
      const relevantTx = rangeTransactions.filter(
        (t) => t.autoPostedSource !== "daily_closing" && t.type !== "transfer",
      );
      const ledgerIncomeTx = relevantTx.filter(
        (t) => t.type === "income" && !isCashAccount(t.toAccountId),
      );
      const ledgerExpenseTx = relevantTx.filter(
        (t) => t.type === "expense" && !isCashAccount(t.fromAccountId),
      );

      // ── Locked closings only for P&L totals ──
      const lockedClosings: FinanceDailyClosing[] = rawClosings.filter((c) => c.locked);
      const lockedClosingsWithSettled = closingsWithSettled.filter((c) => c.locked);

      const closingCashRevenue = roundCurrency(lockedClosings.reduce((s, c) => s + c.cashRevenue, 0));
      const closingUpi = roundCurrency(lockedClosings.reduce((s, c) => s + c.upiSales, 0));
      const closingOther = roundCurrency(lockedClosings.reduce((s, c) => s + c.otherIncome, 0));
      const closingCashExpense = roundCurrency(lockedClosings.reduce((s, c) => s + c.cashExpenseTotal, 0));
      const closingDeposits = roundCurrency(lockedClosings.reduce((s, c) => s + c.depositTotal, 0));

      // Real, settled Zomato/Swiggy revenue only (₹0 for any day whose
      // platform payout hasn't been recorded yet) — see buildSettledRevenueByDate above.
      const settledZomato = roundCurrency(lockedClosingsWithSettled.reduce((s, c) => s + c.zomatoActualRevenue, 0));
      const settledSwiggy = roundCurrency(lockedClosingsWithSettled.reduce((s, c) => s + c.swiggyActualRevenue, 0));

      const closingRevenue = roundCurrency(closingCashRevenue + closingUpi + closingOther + settledZomato + settledSwiggy);

      const ledgerIncome = roundCurrency(ledgerIncomeTx.reduce((s, t) => s + t.amount, 0));
      const ledgerExpense = roundCurrency(ledgerExpenseTx.reduce((s, t) => s + t.amount, 0));

      const totalRevenue = roundCurrency(closingRevenue + ledgerIncome);
      const totalExpense = roundCurrency(closingCashExpense + ledgerExpense);
      const netPnl = roundCurrency(totalRevenue - totalExpense);

      // ── Revenue breakdown ──
      const revenueBreakdown = {
        cashSales: closingCashRevenue,
        upi: closingUpi,
        zomato: settledZomato,
        swiggy: settledSwiggy,
        otherIncome: closingOther,
        ledgerIncome,
      };

      // ── Expense by category (closing cash expenses + ledger expenses) ──
      const closingExpenseItems = lockedClosings.flatMap((c) =>
        c.expenses.map((e) => ({
          label: e.subcategoryName ? `${e.categoryName} › ${e.subcategoryName}` : e.categoryName,
          amount: e.amount,
        })),
      );
      const ledgerExpenseItems = ledgerExpenseTx.map((t) => ({
        label: t.categoryName ?? "Uncategorized",
        amount: t.amount,
      }));
      const expenseByCategory = sumByLabel([...closingExpenseItems, ...ledgerExpenseItems]);

      // ── Income by category (ledger income only — closing already broken down separately) ──
      const ledgerIncomeByCategory = sumByLabel(
        ledgerIncomeTx.map((t) => ({
          label: t.categoryName ?? "Uncategorized",
          amount: t.amount,
        })),
      );

      // ── Deposit breakdown ──
      const depositMap = new Map<string, { label: string; amount: number }>();
      for (const closing of lockedClosings) {
        for (const d of closing.deposits) {
          const existing = depositMap.get(d.type) ?? { label: d.typeLabel, amount: 0 };
          depositMap.set(d.type, { label: d.typeLabel, amount: roundCurrency(existing.amount + d.amount) });
        }
      }
      const depositBreakdown = Array.from(depositMap.values()).sort((a, b) => b.amount - a.amount);

      return NextResponse.json({
        success: true,
        closings: closingsWithSettled, // full rows for day-by-day table (includes drafts), with real settled Zomato/Swiggy revenue attached
        summary: {
          closedDays: lockedClosings.length,
          draftDays: rawClosings.length - lockedClosings.length,
          totalRevenue,
          totalExpense,
          netPnl,
          revenueBreakdown,
          expenseByCategory,
          ledgerIncomeByCategory,
          depositBreakdown,
          closingDeposits,
        },
        accounts: accounts.map((a) => ({ id: a.id, name: a.name, type: a.type, currentBalance: a.currentBalance })),
      });
    } finally {
      await cleanup();
    }
  } catch (error) {
    return financeErrorResponse(error, "/reports/pnl GET");
  }
}
