import { NextResponse } from "next/server";
import { getAuthenticatedFirestoreForRequest } from "@/lib/firebaseServerApp";
import { financeErrorResponse } from "@/lib/financeApiError";
import { toDateKey, roundCurrency, DEFAULT_BRANCH_ID, type FinanceDailyClosing } from "@/lib/finance";
import { buildPlatformDayInfo, lookupPlatformDayInfo } from "@/lib/platformRevenue";
import { getDailyClosingsForRange } from "@/services/financeClosingService";
import { getFinanceAccounts } from "@/services/financeAccountsService";
import { getPostedTransactionsForRange } from "@/services/financeTransactionsService";
import { getZomatoImports, getItemSalesForDateRange } from "@/services/zomatoService";
import { getSwiggyImports, getSwiggyItemSalesForDateRange } from "@/services/swiggyService";

// Platform (Zomato/Swiggy) revenue is settlement-gated — see the big comment
// in lib/platformRevenue.ts (buildPlatformDayInfo) for why `actualNet` (used
// below for Total Revenue / Net P&L / Gross Margin / Revenue Breakdown) must
// be GROSS and ₹0 until settled, not net of deduction. The Finance Dashboard
// (services/financeDashboardService.ts) uses the exact same helper so the
// two pages can never drift out of sync again.

export const dynamic = "force-dynamic";

// ─── Shared aggregation helper (same pattern as financeDashboardService) ──────

function sumByLabel(items: Array<{ label: string; amount: number }>): Array<{ label: string; amount: number }> {
  const totals = new Map<string, number>();
  for (const item of items) {
    totals.set(item.label, roundCurrency((totals.get(item.label) ?? 0) + item.amount));
  }
  return Array.from(totals.entries())
    .map(([label, amount]) => ({ label, amount }))
    .filter((item) => item.amount > 0)
    .sort((a, b) => b.amount - a.amount);
}

// ─── GET /api/finance/reports/pnl ─────────────────────────────────────────────

/**
 * Comprehensive P&L report for a date range.
 *
 * Mirrors the data-blending logic in financeDashboardService:
 *   - Daily Closing (fin_daily_closing): all revenue streams + cash expenses.
 *   - Transactions (fin_transactions): posted income/expense from non-cash
 *     accounts that were NOT auto-generated by Daily Closing itself (those
 *     are already counted in the closing totals — excluding them prevents
 *     double-counting). Transfers are excluded from P&L as always.
 *
 * The two sources are intentionally NOT mixed at the row level — the caller
 * sees closing rows for the day-by-day table and a pre-aggregated summary
 * (with category breakdowns) for the totals sections. The frontend never
 * has to know about account types or auto-post sources.
 */
export async function GET(request: Request) {
  try {
    const { cleanup, firestore } = await getAuthenticatedFirestoreForRequest(request);
    try {
      const url = new URL(request.url);
      const today = toDateKey();
      const dateFrom = url.searchParams.get("dateFrom") ?? today;
      const dateTo = url.searchParams.get("dateTo") ?? today;
      const branchId = DEFAULT_BRANCH_ID;

      // Fetch all sources in parallel
      const [rawClosings, accounts, rangeTransactions, zomatoImports, swiggyImports, zomatoItemSales, swiggyItemSales] = await Promise.all([
        getDailyClosingsForRange(dateFrom, dateTo, firestore, branchId),
        getFinanceAccounts({ branchId }, firestore),
        getPostedTransactionsForRange(dateFrom, dateTo, firestore, branchId),
        getZomatoImports(firestore),
        getSwiggyImports(firestore),
        getItemSalesForDateRange(dateFrom, dateTo, firestore),
        getSwiggyItemSalesForDateRange(dateFrom, dateTo, firestore),
      ]);

      const zomatoClosingGrossByDate = new Map(rawClosings.map((c) => [c.date, c.zomatoSales]));
      const swiggyClosingGrossByDate = new Map(rawClosings.map((c) => [c.date, c.swiggySales]));
      const zomatoByDate = buildPlatformDayInfo(zomatoImports, zomatoItemSales, zomatoClosingGrossByDate);
      const swiggyByDate = buildPlatformDayInfo(swiggyImports, swiggyItemSales, swiggyClosingGrossByDate);

      const closingsWithSettled = rawClosings.map((c) => {
        const zomato = lookupPlatformDayInfo(zomatoByDate, c.date);
        const swiggy = lookupPlatformDayInfo(swiggyByDate, c.date);
        return {
          ...c,
          // actualNet feeds P&L/KPI totals below — GROSS, settled-only (see
          // the big comment above buildPlatformDayInfo for why this must
          // not be net of deduction).
          zomatoActualRevenue: zomato.actualNet,
          swiggyActualRevenue: swiggy.actualNet,
          // displayNet feeds the Daily Breakdown table only — actual once
          // settled, a best-effort estimate until then.
          zomatoDisplayRevenue: zomato.displayNet,
          zomatoDeductionPct: zomato.deductionPct,
          zomatoMode: zomato.mode,
          zomatoSourceStart: zomato.sourceStart,
          zomatoSourceEnd: zomato.sourceEnd,
          swiggyDisplayRevenue: swiggy.displayNet,
          swiggyDeductionPct: swiggy.deductionPct,
          swiggyMode: swiggy.mode,
          swiggySourceStart: swiggy.sourceStart,
          swiggySourceEnd: swiggy.sourceEnd,
        };
      });

      const accountTypeById = new Map(accounts.map((a) => [a.id, a.type]));
      const isCashAccount = (accountId: string | null) =>
        accountId ? accountTypeById.get(accountId) === "cash" : false;

      // Exclude daily_closing auto-posts (already counted in closing totals)
      // and transfers (not P&L items)
      const relevantTx = rangeTransactions.filter(
        (t) => t.autoPostedSource !== "daily_closing" && t.type !== "transfer",
      );
      const ledgerIncomeTx = relevantTx.filter(
        (t) => t.type === "income" && !isCashAccount(t.toAccountId),
      );
      const ledgerExpenseTx = relevantTx.filter(
        (t) => t.type === "expense" && !isCashAccount(t.fromAccountId),
      );

      // ── Locked closings only for P&L totals ──
      const lockedClosings: FinanceDailyClosing[] = rawClosings.filter((c) => c.locked);
      const lockedClosingsWithSettled = closingsWithSettled.filter((c) => c.locked);

      const closingCashRevenue = roundCurrency(lockedClosings.reduce((s, c) => s + c.cashRevenue, 0));
      const closingUpi = roundCurrency(lockedClosings.reduce((s, c) => s + c.upiSales, 0));
      const closingOther = roundCurrency(lockedClosings.reduce((s, c) => s + c.otherIncome, 0));
      const closingCashExpense = roundCurrency(lockedClosings.reduce((s, c) => s + c.cashExpenseTotal, 0));
      const closingDeposits = roundCurrency(lockedClosings.reduce((s, c) => s + c.depositTotal, 0));

      // Gross Zomato/Swiggy revenue, counted only for days whose platform
      // payout has actually been settled (₹0 otherwise) — see
      // buildPlatformDayInfo above. Left as gross (not net of deduction) on
      // purpose: the commission already lands as a separate "Settlement
      // Deduction" expense below, via ledgerExpenseTx.
      const settledZomato = roundCurrency(lockedClosingsWithSettled.reduce((s, c) => s + c.zomatoActualRevenue, 0));
      const settledSwiggy = roundCurrency(lockedClosingsWithSettled.reduce((s, c) => s + c.swiggyActualRevenue, 0));

      const closingRevenue = roundCurrency(closingCashRevenue + closingUpi + closingOther + settledZomato + settledSwiggy);

      const ledgerIncome = roundCurrency(ledgerIncomeTx.reduce((s, t) => s + t.amount, 0));
      const ledgerExpense = roundCurrency(ledgerExpenseTx.reduce((s, t) => s + t.amount, 0));

      const totalRevenue = roundCurrency(closingRevenue + ledgerIncome);
      const totalExpense = roundCurrency(closingCashExpense + ledgerExpense);
      const netPnl = roundCurrency(totalRevenue - totalExpense);

      // ── Revenue breakdown ──
      const revenueBreakdown = {
        cashSales: closingCashRevenue,
        upi: closingUpi,
        zomato: settledZomato,
        swiggy: settledSwiggy,
        otherIncome: closingOther,
        ledgerIncome,
      };

      // ── Expense by category (closing cash expenses + ledger expenses) ──
      const closingExpenseItems = lockedClosings.flatMap((c) =>
        c.expenses.map((e) => ({
          label: e.subcategoryName ? `${e.categoryName} › ${e.subcategoryName}` : e.categoryName,
          amount: e.amount,
        })),
      );
      const ledgerExpenseItems = ledgerExpenseTx.map((t) => ({
        label: t.categoryName ?? "Uncategorized",
        amount: t.amount,
      }));
      const expenseByCategory = sumByLabel([...closingExpenseItems, ...ledgerExpenseItems]);

      // ── Income by category (ledger income only — closing already broken down separately) ──
      const ledgerIncomeByCategory = sumByLabel(
        ledgerIncomeTx.map((t) => ({
          label: t.categoryName ?? "Uncategorized",
          amount: t.amount,
        })),
      );

      // ── Deposit breakdown ──
      const depositMap = new Map<string, { label: string; amount: number }>();
      for (const closing of lockedClosings) {
        for (const d of closing.deposits) {
          const existing = depositMap.get(d.type) ?? { label: d.typeLabel, amount: 0 };
          depositMap.set(d.type, { label: d.typeLabel, amount: roundCurrency(existing.amount + d.amount) });
        }
      }
      const depositBreakdown = Array.from(depositMap.values()).sort((a, b) => b.amount - a.amount);

      return NextResponse.json({
        success: true,
        closings: closingsWithSettled, // full rows for day-by-day table (includes drafts), with real settled Zomato/Swiggy revenue attached
        summary: {
          closedDays: lockedClosings.length,
          draftDays: rawClosings.length - lockedClosings.length,
          totalRevenue,
          totalExpense,
          netPnl,
          revenueBreakdown,
          expenseByCategory,
          ledgerIncomeByCategory,
          depositBreakdown,
          closingDeposits,
        },
        accounts: accounts.map((a) => ({ id: a.id, name: a.name, type: a.type, currentBalance: a.currentBalance })),
      });
    } finally {
      await cleanup();
    }
  } catch (error) {
    return financeErrorResponse(error, "/reports/pnl GET");
  }
}
