import { NextResponse } from "next/server";
import { getAuthenticatedFirestoreForRequest } from "@/lib/firebaseServerApp";
import { financeErrorResponse } from "@/lib/financeApiError";
import { toDateKey, roundCurrency, DEFAULT_BRANCH_ID, type FinanceDailyClosing } from "@/lib/finance";
import { getDailyClosingsForRange } from "@/services/financeClosingService";
import { getFinanceAccounts } from "@/services/financeAccountsService";
import { getPostedTransactionsForRange } from "@/services/financeTransactionsService";
import { getZomatoImports } from "@/services/zomatoService";
import { getSwiggyImports } from "@/services/swiggyService";

// ─── Platform (Zomato/Swiggy) net-of-deduction estimator ──────────────────────
//
// Daily Closing's zomatoSales/swiggySales are a manually entered GROSS figure
// (revenue recognized that day, before the platform's commission/GST/ads cut
// is known). The Daily Breakdown table shows the NET figure instead:
//   - "actual"    — this day falls inside a payout period that has already
//                   been settled (services/zomatoService.ts /
//                   services/swiggyService.ts) — use THAT period's own
//                   deduction % (the real number).
//   - "estimated" — no settlement covers this day yet — use the most
//                   recently settled period's deduction % as a stand-in
//                   ("last week's deduction"), since commission rates don't
//                   swing much week to week.
//   - "unavailable" — no settlement has EVER been recorded for this platform
//                     — nothing to estimate from, so the gross figure is
//                     shown as-is with no deduction applied.
type PlatformMode = "actual" | "estimated" | "unavailable";

interface PlatformImportLike {
  reportStartDate: string;
  reportEndDate: string;
  deductionPct?: number;
}

interface PlatformEstimate {
  net: number;
  pct: number;
  mode: PlatformMode;
  sourceStart: string | null;
  sourceEnd: string | null;
}

function buildPlatformEstimator(imports: PlatformImportLike[]) {
  const settled = imports
    .filter((i) => typeof i.deductionPct === "number")
    .sort((a, b) => b.reportEndDate.localeCompare(a.reportEndDate));
  const mostRecentSettled = settled[0] ?? null;

  return function estimate(date: string, gross: number): PlatformEstimate {
    const covering = imports.find((i) => date >= i.reportStartDate && date <= i.reportEndDate && typeof i.deductionPct === "number");

    if (covering) {
      return {
        net: roundCurrency(gross * (1 - covering.deductionPct!)),
        pct: covering.deductionPct!,
        mode: "actual",
        sourceStart: covering.reportStartDate,
        sourceEnd: covering.reportEndDate,
      };
    }
    if (mostRecentSettled) {
      return {
        net: roundCurrency(gross * (1 - mostRecentSettled.deductionPct!)),
        pct: mostRecentSettled.deductionPct!,
        mode: "estimated",
        sourceStart: mostRecentSettled.reportStartDate,
        sourceEnd: mostRecentSettled.reportEndDate,
      };
    }
    return { net: gross, pct: 0, mode: "unavailable", sourceStart: null, sourceEnd: null };
  };
}

export const dynamic = "force-dynamic";

// ─── Shared aggregation helper (same pattern as financeDashboardService) ──────

function sumByLabel(items: Array<{ label: string; amount: number }>): Array<{ label: string; amount: number }> {
  const totals = new Map<string, number>();
  for (const item of items) {
    totals.set(item.label, roundCurrency((totals.get(item.label) ?? 0) + item.amount));
  }
  return Array.from(totals.entries())
    .map(([label, amount]) => ({ label, amount }))
    .filter((item) => item.amount > 0)
    .sort((a, b) => b.amount - a.amount);
}

// ─── GET /api/finance/reports/pnl ─────────────────────────────────────────────

/**
 * Comprehensive P&L report for a date range.
 *
 * Mirrors the data-blending logic in financeDashboardService:
 *   - Daily Closing (fin_daily_closing): all revenue streams + cash expenses.
 *   - Transactions (fin_transactions): posted income/expense from non-cash
 *     accounts that were NOT auto-generated by Daily Closing itself (those
 *     are already counted in the closing totals — excluding them prevents
 *     double-counting). Transfers are excluded from P&L as always.
 *
 * The two sources are intentionally NOT mixed at the row level — the caller
 * sees closing rows for the day-by-day table and a pre-aggregated summary
 * (with category breakdowns) for the totals sections. The frontend never
 * has to know about account types or auto-post sources.
 */
export async function GET(request: Request) {
  try {
    const { cleanup, firestore } = await getAuthenticatedFirestoreForRequest(request);
    try {
      const url = new URL(request.url);
      const today = toDateKey();
      const dateFrom = url.searchParams.get("dateFrom") ?? today;
      const dateTo = url.searchParams.get("dateTo") ?? today;
      const branchId = DEFAULT_BRANCH_ID;

      // Fetch all sources in parallel
      const [rawClosings, accounts, rangeTransactions, zomatoImports, swiggyImports] = await Promise.all([
        getDailyClosingsForRange(dateFrom, dateTo, firestore, branchId),
        getFinanceAccounts({ branchId }, firestore),
        getPostedTransactionsForRange(dateFrom, dateTo, firestore, branchId),
        getZomatoImports(firestore),
        getSwiggyImports(firestore),
      ]);

      const estimateZomato = buildPlatformEstimator(zomatoImports);
      const estimateSwiggy = buildPlatformEstimator(swiggyImports);

      const closingsWithEstimates = rawClosings.map((c) => {
        const zomato = estimateZomato(c.date, c.zomatoSales);
        const swiggy = estimateSwiggy(c.date, c.swiggySales);
        return {
          ...c,
          zomatoNetRevenue: zomato.net,
          zomatoDeductionPct: zomato.pct,
          zomatoMode: zomato.mode,
          zomatoSourceStart: zomato.sourceStart,
          zomatoSourceEnd: zomato.sourceEnd,
          swiggyNetRevenue: swiggy.net,
          swiggyDeductionPct: swiggy.pct,
          swiggyMode: swiggy.mode,
          swiggySourceStart: swiggy.sourceStart,
          swiggySourceEnd: swiggy.sourceEnd,
        };
      });

      const accountTypeById = new Map(accounts.map((a) => [a.id, a.type]));
      const isCashAccount = (accountId: string | null) =>
        accountId ? accountTypeById.get(accountId) === "cash" : false;

      // Exclude daily_closing auto-posts (already counted in closing totals)
      // and transfers (not P&L items)
      const relevantTx = rangeTransactions.filter(
        (t) => t.autoPostedSource !== "daily_closing" && t.type !== "transfer",
      );
      const ledgerIncomeTx = relevantTx.filter(
        (t) => t.type === "income" && !isCashAccount(t.toAccountId),
      );
      const ledgerExpenseTx = relevantTx.filter(
        (t) => t.type === "expense" && !isCashAccount(t.fromAccountId),
      );

      // ── Locked closings only for P&L totals ──
      const lockedClosings: FinanceDailyClosing[] = rawClosings.filter((c) => c.locked);

      const closingRevenue = roundCurrency(lockedClosings.reduce((s, c) => s + c.totalRevenue, 0));
      const closingCashRevenue = roundCurrency(lockedClosings.reduce((s, c) => s + c.cashRevenue, 0));
      const closingUpi = roundCurrency(lockedClosings.reduce((s, c) => s + c.upiSales, 0));
      const closingZomato = roundCurrency(lockedClosings.reduce((s, c) => s + c.zomatoSales, 0));
      const closingSwiggy = roundCurrency(lockedClosings.reduce((s, c) => s + c.swiggySales, 0));
      const closingOther = roundCurrency(lockedClosings.reduce((s, c) => s + c.otherIncome, 0));
      const closingCashExpense = roundCurrency(lockedClosings.reduce((s, c) => s + c.cashExpenseTotal, 0));
      const closingDeposits = roundCurrency(lockedClosings.reduce((s, c) => s + c.depositTotal, 0));

      const ledgerIncome = roundCurrency(ledgerIncomeTx.reduce((s, t) => s + t.amount, 0));
      const ledgerExpense = roundCurrency(ledgerExpenseTx.reduce((s, t) => s + t.amount, 0));

      const totalRevenue = roundCurrency(closingRevenue + ledgerIncome);
      const totalExpense = roundCurrency(closingCashExpense + ledgerExpense);
      const netPnl = roundCurrency(totalRevenue - totalExpense);

      // ── Revenue breakdown ──
      const revenueBreakdown = {
        cashSales: closingCashRevenue,
        upi: closingUpi,
        zomato: closingZomato,
        swiggy: closingSwiggy,
        otherIncome: closingOther,
        ledgerIncome,
      };

      // ── Expense by category (closing cash expenses + ledger expenses) ──
      const closingExpenseItems = lockedClosings.flatMap((c) =>
        c.expenses.map((e) => ({
          label: e.subcategoryName ? `${e.categoryName} › ${e.subcategoryName}` : e.categoryName,
          amount: e.amount,
        })),
      );
      const ledgerExpenseItems = ledgerExpenseTx.map((t) => ({
        label: t.categoryName ?? "Uncategorized",
        amount: t.amount,
      }));
      const expenseByCategory = sumByLabel([...closingExpenseItems, ...ledgerExpenseItems]);

      // ── Income by category (ledger income only — closing already broken down separately) ──
      const ledgerIncomeByCategory = sumByLabel(
        ledgerIncomeTx.map((t) => ({
          label: t.categoryName ?? "Uncategorized",
          amount: t.amount,
        })),
      );

      // ── Deposit breakdown ──
      const depositMap = new Map<string, { label: string; amount: number }>();
      for (const closing of lockedClosings) {
        for (const d of closing.deposits) {
          const existing = depositMap.get(d.type) ?? { label: d.typeLabel, amount: 0 };
          depositMap.set(d.type, { label: d.typeLabel, amount: roundCurrency(existing.amount + d.amount) });
        }
      }
      const depositBreakdown = Array.from(depositMap.values()).sort((a, b) => b.amount - a.amount);

      return NextResponse.json({
        success: true,
        closings: closingsWithEstimates, // full rows for day-by-day table (includes drafts), with net-of-deduction Zomato/Swiggy estimates attached
        summary: {
          closedDays: lockedClosings.length,
          draftDays: rawClosings.length - lockedClosings.length,
          totalRevenue,
          totalExpense,
          netPnl,
          revenueBreakdown,
          expenseByCategory,
          ledgerIncomeByCategory,
          depositBreakdown,
          closingDeposits,
        },
        accounts: accounts.map((a) => ({ id: a.id, name: a.name, type: a.type, currentBalance: a.currentBalance })),
      });
    } finally {
      await cleanup();
    }
  } catch (error) {
    return financeErrorResponse(error, "/reports/pnl GET");
  }
}
